In [1]:
from ucimlrepo import fetch_ucirepo

# get data

In [2]:
statlog_german_credit_data = fetch_ucirepo(id=144)

In [3]:
type(statlog_german_credit_data)

ucimlrepo.dotdict.dotdict

In [4]:
X = statlog_german_credit_data.data.features 
y = statlog_german_credit_data.data.targets

In [5]:
X.head()

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Attribute11,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,4,A121,67,A143,A152,2,A173,1,A192,A201
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,2,A121,22,A143,A152,1,A173,1,A191,A201
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,3,A121,49,A143,A152,1,A172,2,A191,A201
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,4,A122,45,A143,A153,1,A173,2,A191,A201
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,4,A124,53,A143,A153,2,A173,2,A191,A201

In [6]:
y.head()

   class
0      1
1      2
2      1
3      1
4      2

In [7]:
y.groupby('class').size()

class
1    700
2    300
dtype: int64

In [8]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Attribute1   1000 non-null   str
 1   Attribute2   1000 non-null   int64
 2   Attribute3   1000 non-null   str
 3   Attribute4   1000 non-null   str
 4   Attribute5   1000 non-null   int64
 5   Attribute6   1000 non-null   str
 6   Attribute7   1000 non-null   str
 7   Attribute8   1000 non-null   int64
 8   Attribute9   1000 non-null   str
 9   Attribute10  1000 non-null   str
 10  Attribute11  1000 non-null   int64
 11  Attribute12  1000 non-null   str
 12  Attribute13  1000 non-null   int64
 13  Attribute14  1000 non-null   str
 14  Attribute15  1000 non-null   str
 15  Attribute16  1000 non-null   int64
 16  Attribute17  1000 non-null   str
 17  Attribute18  1000 non-null   int64
 18  Attribute19  1000 non-null   str
 19  Attribute20  1000 non-null   str
dtypes: int64(7), str(13)
memory usage: 156.4 KB

# rename columns from variable descriptions

In [9]:
# Rename the 20 columns in your dataframe
X.columns = [
    "checking_account_status",
    "duration_months",
    "credit_history",
    "purpose",
    "credit_amount",
    "savings_account_bonds",
    "employment_since",
    "installment_rate_percent",
    "personal_status_sex",
    "other_debtors_guarantors",
    "residence_since",
    "property",
    "age_years",
    "other_installment_plans",
    "housing",
    "existing_credits_at_bank",
    "job",
    "liable_persons",
    "telephone",
    "foreign_worker"
]

# map categorical values to definitions

In [10]:
mappings = {
    "checking_account_status": {
        "A11": "<0 DM",
        "A12": "0-200 DM",
        "A13": ">=200 DM",
        "A14": "no account",
    },

    "credit_history": {
        "A30": "no credit/all paid",
        "A31": "bank credit paid",
        "A32": "current credit paid",
        "A33": "past payment delays",
        "A34": "critical/other credit",
    },

    "purpose": {
        "A40": "new car",
        "A41": "used car",
        "A42": "furniture/equipment",
        "A43": "radio/TV",
        "A44": "appliances",
        "A45": "repairs",
        "A46": "education",
        "A47": "vacation",
        "A48": "retraining",
        "A49": "business",
        "A410": "other",
    },

    "savings_account_bonds": {
        "A61": "<100 DM",
        "A62": "100-500 DM",
        "A63": "500-1000 DM",
        "A64": ">=1000 DM",
        "A65": "unknown/no savings",
    },

    "employment_since": {
        "A71": "unemployed",
        "A72": "<1 year",
        "A73": "1-4 years",
        "A74": "4-7 years",
        "A75": ">=7 years",
    },

    "personal_status_sex": {
        "A91": "male divorced",
        "A92": "female married/divorced",
        "A93": "male single",
        "A94": "male married/widowed",
        "A95": "female single",
    },

    "other_debtors_guarantors": {
        "A101": "none",
        "A102": "co-applicant",
        "A103": "guarantor",
    },

    "property": {
        "A121": "real estate",
        "A122": "life insurance/building society",
        "A123": "car/other property",
        "A124": "unknown/no property",
    },

    "other_installment_plans": {
        "A141": "bank",
        "A142": "stores",
        "A143": "none",
    },

    "housing": {
        "A151": "rent",
        "A152": "own",
        "A153": "free",
    },

    "job": {
        "A171": "unemployed/unskilled nonresident",
        "A172": "unskilled resident",
        "A173": "skilled employee/official",
        "A174": "manager/self-employed/highly qualified",
    },

    "telephone": {
        "A191": "none",
        "A192": "registered",
    },

    "foreign_worker": {
        "A201": "yes",
        "A202": "no",
    },
}

In [11]:
for column, mapping in mappings.items():
    X[column] = X[column].map(mapping)

In [12]:
X.head()

,checking_account_status,duration_months,credit_history,purpose,credit_amount,savings_account_bonds,employment_since,installment_rate_percent,personal_status_sex,other_debtors_guarantors,residence_since,property,age_years,other_installment_plans,housing,existing_credits_at_bank,job,liable_persons,telephone,foreign_worker
0,<0 DM,6,critical/other credit,radio/TV,1169,unknown/no savings,>=7 years,4,male single,none,4,real estate,67,none,own,2,skilled employee/official,1,registered,yes
1,0-200 DM,48,current credit paid,radio/TV,5951,<100 DM,1-4 years,2,female married/divorced,none,2,real estate,22,none,own,1,skilled employee/official,1,none,yes
2,no account,12,critical/other credit,education,2096,<100 DM,4-7 years,2,male single,none,3,real estate,49,none,own,1,unskilled resident,2,none,yes
3,<0 DM,42,current credit paid,furniture/equipment,7882,<100 DM,4-7 years,2,male single,guarantor,4,life insurance/building society,45,none,free,1,skilled employee/official,2,none,yes
4,<0 DM,24,past payment delays,new car,4870,<100 DM,1-4 years,3,male single,none,4,unknown/no property,53,none,free,2,skilled employee/official,2,none,yes

In [13]:
y.groupby('class').size()

class
1    700
2    300
dtype: int64

In [14]:
X['bad'] = y['class'].astype(int) - 1

In [15]:
X.groupby('bad').size()

bad
0    700
1    300
dtype: int64

# save data

In [16]:
X.shape

(1000, 21)

In [17]:
X.to_pickle("../data/00_df_data.pkl")

In [18]:
import hashlib

with open("../data/00_df_data.pkl", "rb") as file:
    file_hash = hashlib.sha256(file.read()).hexdigest()

print(file_hash)

c3e59cdf835cb284df60acd7cd5ecde1c1ff36b21901380ea3c0c05ac6609d78

# split into training and tes

In [19]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    X,
    test_size=0.20,
    random_state=42,
    stratify=X["bad"]
)

In [20]:
train_df.to_pickle("../data/00_df_train.pkl")
test_df.to_pickle("../data/00_df_test.pkl")

In [21]:
train_df.groupby('bad').size()

bad
0    560
1    240
dtype: int64

In [22]:
test_df.groupby('bad').size()

bad
0    140
1     60
dtype: int64